### ISSUE TITLE
所有图片链接打不开

### ISSUE THREAD

**Issue by zhuohuwu0603** [sddyljsx/spark-sql-2.3-source-code-interpretation#1]
比如：建议见一个images目录，将图片截图放在其中
https://ws1.sinaimg.cn/large/006tNbRwly1fu6xlztqzyj30ni0ec40y.jpg
https://ws1.sinaimg.cn/large/006tNbRwly1fu6y90emdkj31i20dogq7.jpg
https://ws1.sinaimg.cn/large/006tNbRwly1fu70ydb5wij30os0tewhk.jpg

**Comment by sddyljsx** [comment]
已修复，感谢~
